### ISSUE TITLE
New data dump returns double the sample rate

### ISSUE THREAD

**Issue by Stargon** [jackdwayne/arrhythmia_project#40]
Need to adjust queries done in the views to fix the issue to account for that.

**Comment by Stargon** [comment]
Failing query link: 

* http://localhost:8000/signals/?format=json&signal_record_name_id=100&start=0&end=1

Working queries:

* Patient 103: http://localhost:8000/signals/?format=json&signal_record_name=103&start=0&end=1
* Patient 205: http://localhost:8000/signals/?format=json&signal_record_name=205&start=0&end=1

The failing query link returns the same value as: 

* http://localhost:8000/signals/?format=json&start=0&end=1


Overall, the merge from the pull request #39 works, but the original syntax of how queries is parsed is broken. Either we should fix the query params, fix how the frontend makes the queries, or a mix of both. I think fixing the queries is the easiest route

**Comment by JacksoNoah** [comment]
Issue is not issue. Since there is more than 1 patient you now must specify in the query the patient you want to grab data from.
